# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
#
# USE as ENV["GMAIL_USERNAME"]


# ADMIN_NAME: First User
# ADMIN_EMAIL: user@example.com
# ADMIN_PASSWORD: changeme

SECRET_KEY: 
COOKIE_KEY:
SITE_NAME:

DEVISE_MAILER: 
GMAIL_USERNAME: 
GMAIL_PASSWORD: 
ADMIN_EMAILS: ipetrakov@gmail.com

MANDRILL_USERNAME:
MANDRILL_API_KEY: 

SERVER_IP: 
DEPLOY_USER: 
SSH_PORT: 
DEVISE_SECRET_KEY: 
DEVISE_PEPPER: 